###
POST http://localhost:8080/api/v1/vault/create
Content-Type: application/json

{
  "name": "Test password",
  "description": "Test description",
  "login": "test@gmail.com",
  "password": "testPassword"
}

###
GET http://localhost:8080/api/v1/vault/all

###
GET http://localhost:8080/api/v1/vault/1

###
DELETE http://localhost:8080/api/v1/vault/1

### Find by login
GET http://localhost:8080/api/v1/vault