###
POST http://localhost:8080/api/v1/vault/create
Content-Type: application/json

{
  "name": "Test password",
  "resource": "test-resource.com",
  "description": "Test description",
  "login": "test@gmail.com",
  "password": "testPassword"
}

###
GET http://localhost:8080/api/v1/vault/all

###
GET http://localhost:8080/api/v1/vault/1

###
DELETE http://localhost:8080/api/v1/vault/1

### Find by login
GET http://localhost:8080/api/v1/vault


### Update
PUT http://localhost:8080/api/v1/vault/1
Content-Type: application/json

{
  "name": "Test password Updated REST",
  "resource": "test123",
  "description": "Test description 123",
  "login": "test123@gmail.com",
  "password": "TEST"
}